metricBasePath = 'experiment_data/metrics/';

T_simple = readtable(strcat(metricBasePath, 'simple.csv'));
T_jaccard = readtable(strcat(metricBasePath, 'jaccard.csv'));
T_ssim = readtable(strcat(metricBasePath, 'ssim.csv'));
figure;  
subplot(1,3,1)
%suptitle('Simple Similarity')
boxplot([
    T_simple.HMRF_MCEM_LastSample, ...
    T_simple.HMRF_VEM_LastSample, ...
    T_simple.Grab_Cut, ...
    T_simple.K_Means], ...
    'Notch','on', 'Labels', ...
    {'HMRF-MCEM','HMRF-VEM', 'Grab-Cut', 'K-Means'});
subplot(1,3,2)
%suptitle('Jaccard')
boxplot([
    T_jaccard.HMRF_MCEM_LastSample, ...
    T_jaccard.HMRF_VEM_LastSample, ...
    T_jaccard.Grab_Cut, ...
    T_jaccard.K_Means], ...
    'Notch','on', 'Labels', ...
    {'HMRF-MCEM','HMRF-VEM', 'GrabCut', 'K-Means'});
subplot(1,3,3)
%suptitle('SSIM')
boxplot([
    T_ssim.HMRF_MCEM_LastSample, ...
    T_ssim.HMRF_VEM_LastSample, ...
    T_ssim.Grab_Cut, ...
    T_ssim.K_Means], ...
    'Notch','on', 'Labels', ...
    {'HMRF-MCEM','HMRF-VEM', 'GrabCut', 'K-Means'});

currentFigure = gcf;
title(currentFigure.Children(1), 'SSIM');
title(currentFigure.Children(2), 'Jaccard');
title(currentFigure.Children(3), 'Simple');

stable = [ mean(T_simple.HMRF_MCEM_LastSample) mean(T_jaccard.HMRF_MCEM_LastSample) mean(T_ssim.HMRF_MCEM_LastSample); ...
           mean(T_simple.HMRF_VEM_LastSample) mean(T_jaccard.HMRF_VEM_LastSample) mean(T_ssim.HMRF_VEM_LastSample); ...
           mean(T_simple.HMRF_EM_Expansion) mean(T_jaccard.HMRF_EM_Expansion) mean(T_ssim.HMRF_EM_Expansion);  ...
           mean(T_simple.Grab_Cut) mean(T_jaccard.Grab_Cut) mean(T_ssim.Grab_Cut);  ...
           mean(T_simple.K_Means) mean(T_jaccard.K_Means) mean(T_ssim.K_Means);  ];
latex_table = latex(vpa(sym(stable),3));

boxplot([
    T_simple.HMRF_MCEM_LastSample, ...
    T_simple.HMRF_VEM_LastSample, ...
    T_simple.HMRF_EM_Expansion, ...
    T_simple.Grab_Cut, ...
    T_simple.K_Means], ...
    'Notch','on', 'Labels', ...
    {'HMRF-MCEM','HMRF-VEM','HMRF-EM', 'Grab-Cut', 'K-Means'});

boxplot([
    T_jaccard.HMRF_MCEM_LastSample, ...
    T_jaccard.HMRF_VEM_LastSample, ...
    T_jaccard.HMRF_EM_Expansion, ...
    T_jaccard.Grab_Cut, ...
    T_jaccard.K_Means], ...
    'Notch','on', 'Labels', ...
    {'HMRF-MCEM','HMRF-VEM','HMRF-EM', 'Grab-Cut', 'K-Means'});

boxplot([
    T_ssim.HMRF_MCEM_LastSample, ...
    T_ssim.HMRF_VEM_LastSample, ...
    T_ssim.HMRF_EM_Expansion, ...
    T_ssim.Grab_Cut, ...
    T_ssim.K_Means], ...
    'Notch','on', 'Labels', ...
    {'HMRF-MCEM','HMRF-VEM','HMRF-EM', 'Grab-Cut', 'K-Means'});





